# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBQ5G7suaajML5X7dXmU7bPDbbuaIykb
"""

import networkx as nx
import matplotlib.pyplot as plt

# 1. Load graph (built-in small social network dataset)
G = nx.karate_club_graph()

print(f"Nodes: {G.number_of_nodes()}, Edges: {G.number_of_edges()}")

# 2. Basic analysis
diameter = nx.diameter(G)
avg_clustering = nx.average_clustering(G)
degree_centrality = nx.degree_centrality(G)

print(f"Diameter: {diameter}")
print(f"Average clustering coefficient: {avg_clustering:.3f}")
print("Top 5 nodes by degree centrality:")
top5 = sorted(degree_centrality.items(), key=lambda x: x[1], reverse=True)[:5]
for node, centrality in top5:
    print(f"  Node {node}: {centrality:.3f}")

# 3. Visualization
plt.figure(figsize=(10, 8))
pos = nx.spring_layout(G, seed=42)
node_sizes = [5000 * degree_centrality[n] for n in G.nodes()]
nx.draw(G, pos, with_labels=True, node_color='lightblue',
        node_size=node_sizes, font_size=10, font_weight='bold',
        edge_color='gray')
plt.title(f"Zachary's Karate Club Graph\nDiameter: {diameter}, Avg Clustering: {avg_clustering:.3f}")
plt.savefig("graph_visualization.png", dpi=150)
plt.show()